project:
  type: abnt
abnt:
  titulo: "Naufrágio e resurreição da imagem"
  subtitulo: "a fotografia de Aylan Kurdi inquieta o imaginário contemporâneo"
  autor: "Anna Cristina de Araújo Rodrigues"
  orientador: "Nome do orientador"
  # co-orientador: "Nome do coorientador"
  local: "Brasília, DF"
  data_entrega: "2017, v1.9.2"
  tipo_documento: "Tese (Doutorado)"
  banca:
    - membro: Albert Einstein
      instituicao: Princeton University
    - membro: Paulo Freire
      instituicao: Universidade Federal de Pernambuco   
  elementos-pre-textuais:
    - elementos_pre-textuais/capa.qmd
    # - elementos_pre-textuais/lombada.qmd
    - elementos_pre-textuais/folha_de_rosto.qmd
    # - elementos_pre-textuais/errata.qmd
    - elementos_pre-textuais/folha_de_aprovacao.qmd
    # - elementos_pre-textuais/dedicatoria.qmd
    # - elementos_pre-textuais/epigrafe.qmd
    # - elementos_pre-textuais/agradecimentos.qmd
    - elementos_pre-textuais/resumo.qmd
    - elementos_pre-textuais/abstract.qmd
    # - elementos_pre-textuais/listas.qmd
  elementos-textuais:
    - elementos_textuais/intro.qmd
    - elementos_textuais/imagem.qmd  
  elementos-pos-textuais:
    - elementos_pos-textuais/referencias.qmd
    # - elementos_pos-textuais/glossario.qmd
    # - elementos_pos-textuais/apendice-A.qmd
    # - elementos_pos-textuais/anexo-1.qmd
    # - elementos_pos-textuais/indice.qmd
    # - elementos_pos-textuais/colofao.qmd
  bibliografia: references.bib
format:
  pdf:
    mainfont: "ETbb"
    sansfont: "TeX Gyre Heros"
    sansfontoptions: "Scale=MatchUppercase"
  #     include-in-header: 
        # tex/pacotes.tex
    



